version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - portal-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=./database.sqlite
      - JWT_SECRET=your-secret-key-here
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/database.sqlite:/app/database.sqlite
      - ./client-portal:/app/client-portal
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge
