[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# SPA redirect - všetko ostatné na index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
